name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git remote add space https://$HF_TOKEN@huggingface.co/spaces/Inferno221133/Hiiii
          git push --force space main
